language: python
python:
    - 3.5
    - 3.6
install:
    - pip install -r requirements.txt
script:
    - python -m pytest test/
    - python -m pylint src/ test/
    - python -m pytest --cov=./ test/
after_success:
    - codecov
